name: Other - Build only

on:
  workflow_dispatch:
    branches:
      - 'dev-x86'
  push:
    branches:
      - 'dev-x86'

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push for x86
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms:
            - 'linux/x86'
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pinger:x86