name: Other - Build only

on:
  workflow_dispatch:
    branches:
      - 'dev-arm64'
  push:
    branches:
      - 'dev-arm64'

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push for ARM64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms:
            - 'linux/arm64'
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pinger:arm64